# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 10:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location_lat', models.FloatField(default=0)),
                ('location_lng', models.FloatField(default=0)),
            ],
        ),
    ]
