# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-09-05 17:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='station',
            name='address',
            field=models.TextField(default=datetime.datetime(2016, 9, 5, 17, 21, 37, 420259, tzinfo=utc), max_length=255),
            preserve_default=False,
        ),
    ]
